function resolvedPromise() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ message: 'delayed success!' });
    }, 500);
  });
}

function rejectedPromise() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject(new Error('delayed exception!'));
    }, 500);
  });
}

resolvedPromise()
  .then(result => {
    console.log('Resolved Promise Result:', result);
  })
  .catch(error => {
    console.error('Resolved Promise Error:', error.message);
  });

rejectedPromise()
  .then(result => {
    console.log('Rejected Promise Result:', result);
  })
  .catch(error => {
    console.error('Rejected Promise Error:', error.message);
  });
